wandb_version: 1

dataset_name:
  desc: null
  value: ctxt
n_epochs:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 16
total_seq_length:
  desc: null
  value: 1000
seq_length:
  desc: null
  value: 100
training_help:
  desc: null
  value: 0
hidden_dims:
  desc: null
  value: 100
n_trials:
  desc: null
  value: 200
with_inputnoise:
  desc: null
  value: 1
noise_level:
  desc: null
  value: 10
coherency_intervals:
  desc: null
  value: uniform
optimizer_name:
  desc: null
  value: adagrad
lr:
  desc: null
  value: 0.01
betas:
  desc: null
  value:
  - 0.9
  - 0.999
eps:
  desc: null
  value: 1.0e-07
weight_decay:
  desc: null
  value: 0
amsgrad:
  desc: null
  value: false
momentum:
  desc: null
  value: 0.9
apply_gradient_clipping:
  desc: null
  value: 1
tau:
  desc: null
  value: 10.0
length_skipped_in_data:
  desc: null
  value: 400
hidden_noise:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704323805.661779
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
