wandb_version: 1

dataset_name:
  desc: null
  value: ctxt
n_epochs:
  desc: null
  value: 600
batch_size:
  desc: null
  value: 16
total_seq_length:
  desc: null
  value: 1400
seq_length:
  desc: null
  value: 100
training_help:
  desc: null
  value: 0
hidden_dims:
  desc: null
  value: 100
n_trials:
  desc: null
  value: 5
with_inputnoise:
  desc: null
  value: 1
noise_level:
  desc: null
  value: 2
coherency_intervals:
  desc: null
  value: uniform
optimizer_name:
  desc: null
  value: adagrad
lr:
  desc: null
  value: 0.001
betas:
  desc: null
  value:
  - 0.9
  - 0.999
eps:
  desc: null
  value: 1.0e-07
weight_decay:
  desc: null
  value: 1.0e-06
amsgrad:
  desc: null
  value: false
momentum:
  desc: null
  value: 0.9
apply_gradient_clipping:
  desc: null
  value: 1
tau:
  desc: null
  value: 10.0
length_skipped_in_data:
  desc: null
  value: 100
hidden_noise:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699701346.49803
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 3
      - 5
